version: "3.5"

services:
  api01:
    &api
    image: eigr/spawn-rinha-backend-ex:1.2.1
    restart: always
    hostname: api01
    environment:
      - ACTORS_GLOBAL_BACKPRESSURE_ENABLED=false
      - NODE_COOKIE=cookie-9ce3712b0c3ee21b582c30f942c0d4da-HLuZyQzy+nt0p0r/PVVFTp2tqfLom5igrdmwkYSuO+Q=
      - POD_NAMESPACE=spawn-rinha
      - POD_IP=api01
      - PROXY_ACTOR_SYSTEM_NAME=spawn-rinha
      - PROXY_CLUSTER_STRATEGY=gossip
      - PROXY_DATABASE_TYPE=native
      - PROXY_DATABASE_DATA_DIR=data_1
      - PROXY_HTTP_ACCEPTORS_SIZE=1024
      - PROXY_HTTP_PORT=9090
      - SPAWN_STATESTORE_KEY=3Jnb0hZiHIzHTOih7t2cTEPEpY98Tu1wvQkPfq/XwqE=
    ports:
      - "3001:9090"
    volumes:
      - data_1:/app/data/:rw
      - /tmp:/app/.cache/bakeware/:rw
    deploy:
      resources:
        limits:
          cpus: "0.5"
          #memory: "240MB"
          #memory: "500MB"

  api02:
    <<: *api
    hostname: api02
    environment:
      - ACTORS_GLOBAL_BACKPRESSURE_ENABLED=false
      - NODE_COOKIE=cookie-9ce3712b0c3ee21b582c30f942c0d4da-HLuZyQzy+nt0p0r/PVVFTp2tqfLom5igrdmwkYSuO+Q=
      - POD_NAMESPACE=spawn-rinha
      - POD_IP=api02
      - PROXY_ACTOR_SYSTEM_NAME=spawn-rinha
      - PROXY_CLUSTER_STRATEGY=gossip
      - PROXY_DATABASE_TYPE=native
      - PROXY_DATABASE_DATA_DIR=data_2
      - PROXY_HTTP_ACCEPTORS_SIZE=1024
      - PROXY_HTTP_PORT=9091
      - SPAWN_STATESTORE_KEY=3Jnb0hZiHIzHTOih7t2cTEPEpY98Tu1wvQkPfq/XwqE=
    ports:
      - "3002:9091"
    volumes:
      - data_2:/app/data/:rw
      - /tmp:/app/.cache/bakeware/:rw

  api03:
    <<: *api
    hostname: api03
    environment:
      - ACTORS_GLOBAL_BACKPRESSURE_ENABLED=false
      - NODE_COOKIE=cookie-9ce3712b0c3ee21b582c30f942c0d4da-HLuZyQzy+nt0p0r/PVVFTp2tqfLom5igrdmwkYSuO+Q=
      - POD_NAMESPACE=spawn-rinha
      - POD_IP=api03
      - PROXY_ACTOR_SYSTEM_NAME=spawn-rinha
      - PROXY_CLUSTER_STRATEGY=gossip
      - PROXY_DATABASE_TYPE=native
      - PROXY_DATABASE_DATA_DIR=data_3
      - PROXY_HTTP_ACCEPTORS_SIZE=1024
      - PROXY_HTTP_PORT=9092
      - SPAWN_STATESTORE_KEY=3Jnb0hZiHIzHTOih7t2cTEPEpY98Tu1wvQkPfq/XwqE=
    ports:
      - "3003:9092"
    volumes:
      - data_3:/app/data/:rw
      - /tmp:/app/.cache/bakeware/:rw

  api04:
    <<: *api
    hostname: api04
    environment:
      - ACTORS_GLOBAL_BACKPRESSURE_ENABLED=false
      - NODE_COOKIE=cookie-9ce3712b0c3ee21b582c30f942c0d4da-HLuZyQzy+nt0p0r/PVVFTp2tqfLom5igrdmwkYSuO+Q=
      - POD_NAMESPACE=spawn-rinha
      - POD_IP=api04
      - PROXY_ACTOR_SYSTEM_NAME=spawn-rinha
      - PROXY_CLUSTER_STRATEGY=gossip
      - PROXY_DATABASE_TYPE=native
      - PROXY_DATABASE_DATA_DIR=data_4
      - PROXY_HTTP_ACCEPTORS_SIZE=1024
      - PROXY_HTTP_PORT=9093
      - SPAWN_STATESTORE_KEY=3Jnb0hZiHIzHTOih7t2cTEPEpY98Tu1wvQkPfq/XwqE=
    ports:
      - "3004:9093"
    volumes:
      - data_4:/app/data/:rw
      - /tmp:/app/.cache/bakeware/:rw

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
      - api03
      - api04
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "20MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1

volumes:
  data_1:
  data_2:
  data_3:
  data_4:
