version: "3.5"

services:
  api01:
    &api
    image: eigr/spawn-rinha-backend-ex:1.1.1
    hostname: api01
    environment:
      - PROXY_ACTOR_SYSTEM_NAME=spawn-rinha
      - PROXY_CLUSTER_STRATEGY=gossip
      - PROXY_DATABASE_NAME=rinha
      - PROXY_DATABASE_PORT=5432
      - PROXY_DATABASE_SECRET=123
      - PROXY_DATABASE_TYPE=postgres
      - PROXY_DATABASE_USERNAME=admin
      - PROXY_HTTP_PORT=9090
      - SPAWN_STATESTORE_KEY=3Jnb0hZiHIzHTOih7t2cTEPEpY98Tu1wvQkPfq/XwqE=
    ports:
      - "3001:9090"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "200MB"

  api02:
    <<: *api
    hostname: api02
    environment:
      - PROXY_ACTOR_SYSTEM_NAME=spawn-rinha
      - PROXY_CLUSTER_STRATEGY=gossip
      - PROXY_DATABASE_NAME=rinha
      - PROXY_DATABASE_PORT=5432
      - PROXY_DATABASE_SECRET=123
      - PROXY_DATABASE_TYPE=postgres
      - PROXY_DATABASE_USERNAME=admin
      - PROXY_HTTP_PORT=9090
      - SPAWN_STATESTORE_KEY=3Jnb0hZiHIzHTOih7t2cTEPEpY98Tu1wvQkPfq/XwqE=
    ports:
      - "3002:9090"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "140MB"

networks:
  default:
    driver: bridge
    name: spawn-rinha-2024q1
