version: "3.5"

services:
  api01:
    &api
    image: eigr/spawn-rinha-backend-ex:1.2.1
    restart: always
    hostname: api01
    environment:
      - ACTORS_GLOBAL_BACKPRESSURE_ENABLED=true
      - NODE_COOKIE=cookie-9ce3712b0c3ee21b582c30f942c0d4da-HLuZyQzy+nt0p0r/PVVFTp2tqfLom5igrdmwkYSuO+Q=
      - POD_NAMESPACE=spawn-rinha
      - PROXY_ACTOR_SYSTEM_NAME=spawn-rinha
      - PROXY_CLUSTER_STRATEGY=gossip
      - PROXY_DATABASE_TYPE=native
      - PROXY_HTTP_ACCEPTORS_SIZE=600
      - PROXY_HTTP_PORT=9090
      - SPAWN_STATESTORE_KEY=3Jnb0hZiHIzHTOih7t2cTEPEpY98Tu1wvQkPfq/XwqE=
    ports:
      - "3001:9090"
    volumes:
      - ./data:/app/data/:rw
      - /tmp:/app/.cache/bakeware/:rw
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "220MB"

  api02:
    <<: *api
    hostname: api02
    environment:
      - ACTORS_GLOBAL_BACKPRESSURE_ENABLED=true
      - NODE_COOKIE=cookie-9ce3712b0c3ee21b582c30f942c0d4da-HLuZyQzy+nt0p0r/PVVFTp2tqfLom5igrdmwkYSuO+Q=
      - POD_NAMESPACE=spawn-rinha
      - PROXY_ACTOR_SYSTEM_NAME=spawn-rinha
      - PROXY_CLUSTER_STRATEGY=gossip
      - PROXY_DATABASE_TYPE=native
      - PROXY_HTTP_ACCEPTORS_SIZE=600
      - PROXY_HTTP_PORT=9091
      - SPAWN_STATESTORE_KEY=3Jnb0hZiHIzHTOih7t2cTEPEpY98Tu1wvQkPfq/XwqE=
    ports:
      - "3002:9090"

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "60MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
