version: "3.5"

services:
  api01:
    &api
    image: eigr/spawn-rinha-backend-ex:1.3.2
    restart: always
    hostname: api01
    environment:
      - ACTORS_GLOBAL_BACKPRESSURE_ENABLED=false
      - NODE_COOKIE=cookie-9ce3712b0c3ee21b582c30f942c0d4da-HLuZyQzy+nt0p0r/PVVFTp2tqfLom5igrdmwkYSuO+Q=
      - POD_NAMESPACE=spawn-rinha
      - POD_IP=api01
      - PROXY_ACTOR_SYSTEM_NAME=spawn-rinha
      - PROXY_CLUSTER_STRATEGY=gossip
      - PROXY_DATABASE_TYPE=native
      - PROXY_DATABASE_DATA_DIR=data_1
      - PROXY_HTTP_ACCEPTORS_SIZE=3500
      - PROXY_HTTP_UDS_ENABLED=true
      - PROXY_HTTP_UDS_SOCK_ADDR=/var/run/api01.sock
      - PROXY_HTTP_PORT=9090
      - SPAWN_STATESTORE_KEY=3Jnb0hZiHIzHTOih7t2cTEPEpY98Tu1wvQkPfq/XwqE=
    ports:
      - "3001:9090"
    volumes:
      - data_1:/app/data/:rw
      - /tmp:/app/.cache/bakeware/:rw
      - ${PWD}/sockets/api01:/var/run/api01.sock:rw
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--no-buffer",
          "-XGET",
          "--unix-socket",
          "${PWD}/sockets/api01",
          "http://api01/health/readiness"
        ]
      interval: 15s
      timeout: 5s
      retries: 30
    deploy:
      resources:
        limits:
          cpus: "0.675"
          memory: "265MB"

  api02:
    <<: *api
    hostname: api02
    environment:
      - ACTORS_GLOBAL_BACKPRESSURE_ENABLED=false
      - NODE_COOKIE=cookie-9ce3712b0c3ee21b582c30f942c0d4da-HLuZyQzy+nt0p0r/PVVFTp2tqfLom5igrdmwkYSuO+Q=
      - POD_NAMESPACE=spawn-rinha
      - POD_IP=api02
      - PROXY_ACTOR_SYSTEM_NAME=spawn-rinha
      - PROXY_CLUSTER_STRATEGY=gossip
      - PROXY_DATABASE_TYPE=native
      - PROXY_DATABASE_DATA_DIR=data_2
      - PROXY_HTTP_ACCEPTORS_SIZE=3500
      - PROXY_HTTP_UDS_ENABLED=true
      - PROXY_HTTP_UDS_SOCK_ADDR=/var/run/api02.sock
      - PROXY_HTTP_PORT=9091
      - SPAWN_STATESTORE_KEY=3Jnb0hZiHIzHTOih7t2cTEPEpY98Tu1wvQkPfq/XwqE=
    ports:
      - "3002:9091"
    volumes:
      - data_2:/app/data/:rw
      - ${PWD}/sockets/api02:/var/run/api02.sock:rw
      - /tmp:/app/.cache/bakeware/:rw
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--no-buffer",
          "-XGET",
          "--unix-socket",
          "${PWD}/sockets/api02",
          "http://api02/health/readiness"
        ]
      interval: 15s
      timeout: 5s
      retries: 30

  haproxy:
    image: haproxy:3.0-dev2-alpine
    depends_on:
      api01:
        condition: service_healthy
      api02:
        condition: service_healthy
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ${PWD}/sockets/api01:/var/run/api01.sock:rw
      - ${PWD}/sockets/api02:/var/run/api02.sock:rw
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "20MB"

networks:
  default:
    driver: bridge
    name: rinha-spawn-2024q1

volumes:
  data_1:
  data_2:
